### ISSUE TITLE
Empty local with django 1.10 and Python 3.5

### ISSUE THREAD

**Issue by ldng** [nigma/django-request-id#5]
Python : 3.5.1
Django: 1.10.2

get_current_request_id always returns '' since local.request_id raise an AttributeError.
In views request.request_id is set to the correct value.

in RequestIdMiddleware.**call** :
![capture](https://cloud.githubusercontent.com/assets/781064/19774189/82e33c58-9c6c-11e6-9892-c4a99cdcfcf6.png)

In our view :
![capture-1](https://cloud.githubusercontent.com/assets/781064/19774188/82e20644-9c6c-11e6-8c1b-f64da10f9ee2.png)

In get_current_request_id called from RequestIdFilter.filter :
![capture-2](https://cloud.githubusercontent.com/assets/781064/19774187/828bcafe-9c6c-11e6-88a8-5bed38dfed71.png)

**Comment by nigma** [comment]
Hey Idng. Thanks for the screenshots. This is strange. I have a couple follow up questions:
- Is this happening on the Django dev server?
- How does the list of `MIDDLEWARE` look like?
- Are you using any asynchronous libraries like gevent?

The `local.request_id` should be empty only if the logging is happening at a layer above the `RequestIdMiddleware` or there is some unexpected thread context switch.

**Comment by ldng** [comment]
Sorry, been busy and kind of dropped the ball for a moment.
This was also happening with the dev server.
MIDDLEWARE = [
    'request_id.middleware.RequestIdMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]
We are note using any asynchronous libraries.

But now I can not reproduce it. Maybe a borked install ? 
It's weird. Well, I'll close since an unreproducible bug is not very useful.
